### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by YT-Advanced** [euzun/jpgscraper#1]
Hello, I am interested in your JPEG Carver C# tool and want to add it into my project. But I don't know how to use your source code. Can you help me to use this and many thanks

**Comment by euzun** [comment]
If you can elaborate your project a little bit, I can help better.

**Comment by YT-Advanced** [comment]
> ‎Nếu bạn có thể xây dựng dự án của bạn một chút, tôi có thể giúp đỡ tốt hơn.‎

I have build my C# App, and now I want to add your class and file to my app but I don't know how to use it

**Comment by YT-Advanced** [comment]
> If you can elaborate your project a little bit, I can help better.

Here is my app and can you add your class into my app
https://github.com/YT-Advanced/Testapp
